# Generated by Django 4.2.8 on 2024-02-27 21:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desarrollo', '0001_initial'),
    ]

    operations = [
       # migrations.AddField(
        #    model_name='segagen',
         #   name='id',
          #  field=models.BigAutoField(auto_created=True, default=datetime.datetime(2024, 2, 27, 21, 27, 7, 500943, tzinfo=datetime.timezone.utc), primary_key=True, serialize=False, verbose_name='ID'),
           # preserve_default=False,
        #),
        #migrations.AddField(
         #   model_name='segerror',
          #  name='id',
           # field=models.BigAutoField(auto_created=True, default=datetime.datetime(2024, 2, 27, 21, 27, 37, 55095, tzinfo=datetime.timezone.utc), primary_key=True, serialize=False, verbose_name='ID'),
            #preserve_default=False,
        #),
    ]
