"""
Django settings for modulo_seguridad project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-d#g^gcs6j#lbi3hz_94lm@kq+sgjr0$*qc!fyr7w0n@z=7i772'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = [
    '103.23.61.168',
    '127.0.0.1',
    '5e9147f5-145d-4231-97c5-0bdcffd88b89.clouding.host'
]

SECURE_PROXY_SSL_HEADER=('HTTP_X_FORWARDED_PROTO','https')
SECURE_HSTS_SECONDS=259200
SECURE_SSL_REDIRECT=True
SESSION_COOKIE_SECURE=True
CSRF_COOKIE_SECURE=True

HTTPS_PORT = 443
HTTPS_SSL_CERTFILE = '/etc/letsencrypt/live/5e9147f5-145d-4231-97c5-0bdcffd88b89.clouding.host/fullchain.pem'
HTTPS_SSL_KEYFILE = '/etc/letsencrypt/live/5e9147f5-145d-4231-97c5-0bdcffd88b89.clouding.host/privkey.pem'
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'desarrollo',
    'rest_framework',
    'copadasa',
    'sslserver',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOWED_ORIGINS = [
    'https://127.0.0.1:8080', # Agrega el dominio de tu aplicación Vue.js
    'http://103.23.61.168:8080', # Agrega el dominio de tu aplicación Vue.js
    'https://5e9147f5-145d-4231-97c5-0bdcffd88b89.clouding.host'
]

CORS_ALLOW_METHODS = (
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
)

CORS_ALLOW_CREDENTIALS = True

ROOT_URLCONF = 'modulo_seguridad.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'modulo_seguridad.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
     'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME':'teampy',
        'USER':'postgres',
        'PASSWORD':'postgres',
        'HOST':'127.0.0.1',
        'PORT':'5432',
         'OPTIONS': {
            'sslmode': 'require',
            'sslcert': '/etc/letsencrypt/live/5e9147f5-145d-4231-97c5-0bdcffd88b89.clouding.host/cert.pem',
            'sslkey': '/etc/letsencrypt/live/5e9147f5-145d-4231-97c5-0bdcffd88b89.clouding.host/privkey.pem',
        },
    },
     'copadasa_db': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME':'copadasapma',
        'USER':'postgres',
        'PASSWORD':'postgres',
        'HOST':'127.0.0.1',
        'PORT':'5432',
         'OPTIONS': {
            'sslmode': 'require',
            'sslcert': '/etc/letsencrypt/live/5e9147f5-145d-4231-97c5-0bdcffd88b89.clouding.host/cert.pem',
            'sslkey': '/etc/letsencrypt/live/5e9147f5-145d-4231-97c5-0bdcffd88b89.clouding.host/privkey.pem',
        },
     }
}      

DATABASE_ROUTERS = ['copadasa.routers.CopadasaRouter',]

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

DATE_FORMAT = 'd/m/Y'

TIME_FORMAT = 'H:i:s'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'contesispty@gmail.com'  # Tu correo
EMAIL_HOST_PASSWORD = 'mwnywlugasyvqxpo'   # Tu contraseña
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER


'''LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django.db.backends': {
            'handlers': ['console'],
            'level': 'DEBUG',
        },
    },
    'root':{
        'handlers': ['console'],
        'level': 'DEBUG',
    }
}'''




